"""Deterministic tool functions the agent calls for math it must not do
itself: scaling ingredient amounts to household size, picking the cheapest
product that covers the needed quantity, and summing the final cart total
against the user's budget.

This mirrors the project's own risk-mitigation note (모델 출력 위험): the LLM
decides *when* to call these and *which* ingredient/candidates to pass in,
but every number that ends up in front of the user is computed here in
plain Python, not generated by the model.
"""
import math

# Rough same-family unit conversions used only to size how many packages of
# a matched product are needed. Cross-family conversions (e.g. 개 -> g)
# aren't attempted; in that case we conservatively assume one package.
_UNIT_TO_BASE: dict[str, tuple[str, float]] = {
    "g": ("g", 1), "kg": ("g", 1000),
    "ml": ("ml", 1), "l": ("ml", 1000),
    "큰술": ("ml", 15), "작은술": ("ml", 5), "컵": ("ml", 200),
}


def _normalize(text: str) -> str:
    return (text or "").strip().lower()


def _contains_any(name: str, terms: list[str]) -> bool:
    normalized = _normalize(name)
    return any(_normalize(term) in normalized for term in terms if term)


def _quantity_needed(scaled_amount: float | None, ing_unit: str | None, pkg_amount: float | None, pkg_unit: str | None) -> int:
    if scaled_amount is None or pkg_amount is None or not pkg_unit or not ing_unit:
        return 1
    ing_base = _UNIT_TO_BASE.get(_normalize(ing_unit))
    pkg_base = _UNIT_TO_BASE.get(_normalize(pkg_unit))
    if ing_base is None or pkg_base is None or ing_base[0] != pkg_base[0]:
        return 1
    needed_base = scaled_amount * ing_base[1]
    pkg_base_amount = pkg_amount * pkg_base[1]
    if pkg_base_amount <= 0:
        return 1
    return max(1, math.ceil(needed_base / pkg_base_amount))


def scale_ingredient_amount(amount: float | None, recipe_servings: float, household_size: float) -> dict:
    """레시피 재료량을 사용자 가구 인원수에 맞게 환산한다.

    Args:
        amount: 레시피 기준 재료량 (예: 돼지고기 300g이면 300). 알 수 없으면 None.
        recipe_servings: 레시피가 기준으로 하는 인분 수 (예: 2).
        household_size: 사용자의 실제 가구 인원수 (예: 4).

    Returns:
        scaled_amount(환산된 양), scale_factor(배율)를 담은 dict.
    """
    scale_factor = (household_size / recipe_servings) if recipe_servings else 1.0
    scaled = round(amount * scale_factor, 4) if amount is not None else None
    return {"scaled_amount": scaled, "scale_factor": scale_factor}


def pick_cheapest_product(
    needed_amount: float | None,
    needed_unit: str | None,
    candidates: list[dict],
    exclude_terms: list[str],
) -> dict:
    """후보 상품 중 필요한 양을 채우는 데 드는 총 비용이 가장 싼 것을 고른다.

    Args:
        needed_amount: 환산된 필요 수량 (scale_ingredient_amount의 결과).
        needed_unit: 재료 단위 (예: "g", "개").
        candidates: 상품 후보 목록. 각 항목은
            {product_id, name, price, pkg_amount, pkg_unit, vendor, url} 형태.
        exclude_terms: 상품명에 포함되면 제외할 단어 목록 (알레르기·제외 재료 등).

    Returns:
        선택된 상품과 필요 수량, 소계(subtotal)를 담은 dict. 안전한 후보가
        없으면 {"skipped_reason": ...}를 담은 dict.
    """
    safe_candidates = [c for c in candidates if not _contains_any(c.get("name", ""), exclude_terms)]
    if not safe_candidates:
        reason = "알레르기/제외 조건을 만족하는 상품을 찾지 못함" if candidates else "매칭되는 상품을 찾지 못함"
        return {"selected": None, "quantity": 0, "subtotal": 0, "skipped_reason": reason}

    best = None
    best_qty = 1
    best_cost = None
    for candidate in safe_candidates:
        qty = _quantity_needed(needed_amount, needed_unit, candidate.get("pkg_amount"), candidate.get("pkg_unit"))
        cost = candidate.get("price", 0) * qty
        if best_cost is None or cost < best_cost:
            best, best_qty, best_cost = candidate, qty, cost

    return {
        "selected": best,
        "quantity": best_qty,
        "subtotal": best_cost,
        "skipped_reason": None,
    }


def summarize_cart(selections: list[dict], budget: float | None) -> dict:
    """선택된 상품들의 소계를 합산하고 예산 이내인지 계산한다.

    Args:
        selections: pick_cheapest_product가 반환한 dict들의 목록
            (subtotal 필드를 사용해 합산한다. skipped된 항목도 포함해도 됨).
        budget: 사용자가 입력한 예산. 없으면 None.

    Returns:
        total_price(총액), budget, within_budget(예산 이내 여부)를 담은 dict.
    """
    total = sum(s.get("subtotal") or 0 for s in selections)
    within_budget = (total <= budget) if budget is not None else None
    return {"total_price": total, "budget": budget, "within_budget": within_budget}
